WITH CUSTOMERS AS (
    SELECT * FROM {{ref('stage_customers')}}
),

ORDERS AS (
    SELECT * FROM {{ref('stage_orders')}}
),

-- TO FIND MIN, MAX ORDER_DATE , COUNT_OF_ORDER_PER_DAY
CUSTOMER_ORDER AS (
    SELECT CUSTOMER_ID , 
           MIN(ORDER_DATE) AS FIRST_ORDER_DATE ,
           MAX(ORDER_DATE) AS MOST_RECENT_ORDER_DATE,
           COUNT(ORDER_ID) AS NO_OF_ORDERS_PER_DAY
    FROM ORDERS 
    GROUP BY 1

),

FINAL_C AS (
    SELECT C.CUSTOMER_ID AS CUSTOMER_ID, 
           C.FIRST_NAME AS CUST_FIRST_NAME ,
           C.LAST_NAME AS CUST_LAST_NAME ,
           CO.FIRST_ORDER_DATE  AS CUST_FIRST_ORDER,
           CO.MOST_RECENT_ORDER_DATE AS CUST_MOST_RECENT_ORDER,
           COALESCE(CO.NO_OF_ORDERS_PER_DAY,0 ) AS NO_OF_ORDERS_PER_DAY      
    FROM CUSTOMERS C
    LEFT JOIN CUSTOMER_ORDER CO USING (CUSTOMER_ID)
    
    
)
SELECT * FROM FINAL_C